import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Appbar } from "@/components/Appbar";
const inter = Inter({ subsets: ["latin"] });
import Image from "next/image";
import image from "./image.png"
import second from './second.png'

import { CookiesProvider } from "./cookiecontext";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; 
}>) {
  return (
    <html lang="en">
       
      <body > 
        <CookiesProvider>
        <div className="flex-col w-screen h-screen overflow-x-hidden">
          <Appbar/>
          {children}
        </div>
        </CookiesProvider>
      </body>
      {/* <body><Test/></body> */}
    </html>
  );
}
